### ISSUE TITLE
[Saving/Backups] Very long save times

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/PAYDAY-2-BeardLib-Editor#264]
For example a project I have has 7 levels (with 6 of them being made into instances) and the saving starts with about 2s of freezing and then takes about 10s to save until the save icon starts fading from blue.

**Comment by ontrigger** [comment]
Does the content of these levels matter or is it just the amount?

**Comment by RexTheWho** [comment]
Finally able to comment.
The main level is very large but the instances are only ~200 units/elements so saving in its own shouldnt be an issue if it was a standalone level.

**Comment by RexTheWho** [comment]
Update: I think one of the causes for save lag may actually be excess extract loading, If I have a level with more than 100 extract loaded units saving slows down considerably.

**Comment by Luffyyy** [comment]
TODO: save individual level instead of the whole map.

**Comment by RexTheWho** [comment]
More tests, Having a large list of extract loaded units causes save times even on a small map to be excruciatingly long.

**Comment by RexTheWho** [comment]
Not an issue, Backups cause saving to take longer and seems fair if your level has a lot of stuff.
