### ISSUE TITLE
Job Wrapper Issue

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/PAYDAY-2-BeardLib-Editor#271]
Trying to find a way to use Job wrappers for randomly selected narratives but cant seem to find any way around this issue.

In the narrative Tweakdata you sometimes see a wrapper contract that has no chain and includes other jobs in the job_wrapper section.

```
	self.jobs.watchdogs_wrapper = {
		name_id = "heist_watchdogs",
		briefing_id = "heist_watchdogs_crimenet",
		contact = "hector",
		region = "dock",
		jc = 50,
		chain = {{}},
		job_wrapper = {
			"watchdogs",
			"watchdogs_night"
		},
```

Afaik the issue here is when you have a blank chain the job doesnt show in crimenet.

Another issue is you cant seem to hide Jobs either so the 2 variations of the Job will also be visible in crimenet.
Using `hidden = true` causes a crash if you try that.

**Comment by Luffyyy** [comment]
Next BeardLib update should allow narratives with empty chain to work
Also addition of "hide_from_crimenet" value to hide narratives from crimenet.
In the future I might also change the way projects are edited in the editor to allow adding additional narratives and make things like escape levels.
