### ISSUE TITLE
Crash on adding new continent

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/PAYDAY-2-BeardLib-Editor#313]
Made a new project + level, tried to add a new continent called "mockup" and then crashed. Tried again but still crashing.

**Comment by Luffyyy** [comment]
Doesn't crash. Always provide a crashlog.

**Comment by RexTheWho** [comment]
Currently dont have the crashlog (at some point cleared my logs just after) so until I have this issue again Ill close it since you say its not crashing.
