### ISSUE TITLE
[UI] Element InstancePoint selection box cuts text off

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/PAYDAY-2-BeardLib-Editor#323]
When trying to find instances that have a long name the text is cut off, usually is an important bit since names have a _001 format that gets cut off.

![image](https://user-images.githubusercontent.com/26837908/55835426-babc7380-5b4e-11e9-9823-001f7f89020e.png)

**Comment by Luffyyy** [comment]
Issue that will be fixed in the future in BeardLib.
