### ISSUE TITLE
[UI] World-main page will sometimes go to World-AI page when copy/pasting units/elements

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/PAYDAY-2-BeardLib-Editor#327]
repro is simple, select a unit or element, copy them with CTRL+C and paste them with CTRL+V. this will usually make the World-Main page switch to the World-AI page even when you're not viewing the World page.

**Comment by Luffyyy** [comment]
lol I found out the select unit menu opens up if you press ctrl+v
either gonna try fixing that or remap it
