### ISSUE TITLE
[Misc issue] Game only renders units inside the portal that the editor camera is inside of while playtesting

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/PAYDAY-2-BeardLib-Editor#328]
very recent versions of beardlib editor (from the past 2-3 days) seem to be having this problem. if i go to playtest on a heist with portals (Panic room for example) but leave my editor camera in a spot where it would not render parts of the level and i go to playtest it i'll notice anything that should be rendered (like the exterior of the building in panic room if you leave your camera far out enough in the front streets, default position that the camera starts in will cause this as well) aren't being rendered.

**Comment by Luffyyy** [comment]
This has been fixed but it might still be visible when switching playtesting to editor and then back, walking around the map *should* resolve these.
