### ISSUE TITLE
[UI] Random crashes from Scrollablepanel

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/PAYDAY-2-BeardLib-Editor#329]
one of my crashes was this (an access violation)
`Script stack:
               mouse_pressed()  lib/managers/menu/scrollablepanel.lua:451           
                MousePressed()  1183                                                
                MousePressed()  1182                                                
                MousePressed()  1182                                                
                MousePressed()  1182                                                
                 mouse_press()  429                                                 
                                lib/managers/mousepointermanager.lua:339   `
this can be some very simple things like pressing my mouse or using the scrollwheel on my mouse.

**Comment by Luffyyy** [comment]
BeardLib issues, should be fixed in latest commit. If not open issue there.
