### ISSUE TITLE
[Undo/Redo] Moving multiple units in menu doesnt undo/redo

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/PAYDAY-2-BeardLib-Editor#336]
When selecting lots of units and then move them with the translate coordinates does not fully undo/redo.

-Select more than 1 prop
-Go to the Translate section and change its location
-Deselect
-Undo (fails to return their position)

**Comment by Luffyyy** [comment]
Seems to work fine for me

**Comment by Luffyyy** [comment]
Latest update fixed some other issues for undo/redo it might've fixed this issue. Please check.

**Comment by RexTheWho** [comment]
Undo-Redo seems to work fine now, Been using it without any issues so far.
