### ISSUE TITLE
[Unit/Element transformation] translate/rotation value copy/paste buttons do nothing

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/PAYDAY-2-BeardLib-Editor#338]
repro is simple, select a unit or element, press "c" and then either move the unit/element you have selected and press "p" nothing will happen with translate, didn't test with rotation but i'm willing to bet the same thing happens.

**Comment by RexTheWho** [comment]
More details I guess, Copying just copies "nil".

**Comment by Luffyyy** [comment]
Should be fixed
