### ISSUE TITLE
[UI] Broken Portal UI

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/PAYDAY-2-BeardLib-Editor#341]
Unable to edit portal shapes due to this issue:
![image](https://user-images.githubusercontent.com/26837908/57980884-839d8400-7a63-11e9-9b3d-ae7209c3f390.png)

This doesnt seem to be exclusive to portal shapes, Ive seen it happen to Linked By/Linking To element lists but it isnt as common.

This is from a fresh copy of Beardlib+Editor

**Comment by Luffyyy** [comment]
Fixed in last commit
